#ifndef LABBB_MAIN_HEADER_H
#define LABBB_MAIN_HEADER_H
#include "stdio.h"
#include "string.h"
#include "structure_functions.h"
#include "memory_functions.h"
#include "process_text.h"
#include "memory_allocation_for_text.h"
#include "stdio.h"
#include "malloc.h"
#include "error_output.h"
#include "define.h"
#include "ctype.h"
#endif //LABBB_MAIN_HEADER_H
